import type { Metadata } from "next";
<<<<<<< HEAD
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
=======
import { Geist } from "next/font/google";
import "./globals.css";
import { Header } from "../components/Header";

const geist = Geist({
>>>>>>> v2
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Create Next App",
  description: "Generated by create next app",
=======
  title: "John Lira",
  description: "My personal site",
>>>>>>> v2
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
<<<<<<< HEAD
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
=======
        className={`${geist.className}  antialiased  transition-all  duration-150`}
      >
        <div className="relative mx-auto flex flex-col gap-20 items-center  min-h-screen  w-[95%] max-w-5xl">
          <Header />
          {children}
        </div>
>>>>>>> v2
      </body>
    </html>
  );
}
